import DashboardLayout from "@/components/DashboardLayout";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { cn } from "@/lib/utils";
import { trpc } from "@/lib/trpc";
import { ArchiveRestore, CheckCircle2, FileKey2, KeyRound, LockKeyhole, ShieldCheck, UserRoundPlus, UsersRound } from "lucide-react";
import { toast } from "sonner";
import { useLocation } from "wouter";

export default function AdministrationPage({ preview = false }: { preview?: boolean }) {
  const [, navigate] = useLocation();
  const audits = trpc.nodescope.audit.list.useQuery({ limit: 20 }, { enabled: !preview, refetchInterval: 8_000 });
  const backup = trpc.nodescope.backups.initiate.useMutation({
    onSuccess: () => toast.success("Backup operation queued", { description: "The intent has been written to the audit trail." }),
    onError: (error) => toast.error("Unable to queue backup", { description: error.message }),
  });
  const policy = [
    { role: "Viewer", detail: "Read fleet, host, history, alert, and audit information.", tone: "text-slate-200" },
    { role: "Operator", detail: "Viewer permissions plus alerts, intervals, baselines, and approved operational workflows.", tone: "text-cyan-100" },
    { role: "Administrator", detail: "Operator permissions plus identities, credentials, routes, policies, certificates, and backups.", tone: "text-violet-100" },
  ];
  return <DashboardLayout><div className="mx-auto max-w-[1320px] p-6 xl:p-8">
    <header className="flex flex-col gap-4 border-b border-white/8 pb-6 md:flex-row md:items-end md:justify-between"><div><div className="flex items-center gap-2 text-violet-100"><ShieldCheck className="h-4 w-4" /><span className="text-xs font-medium tracking-[0.12em]">FLEET-WIDE AUTHORIZATION</span></div><h1 className="mt-3 text-3xl font-semibold tracking-[-0.035em] text-slate-50">Administration</h1><p className="mt-2 max-w-2xl text-sm leading-6 text-slate-400">Identity, credentials, audit, backup, and policy operations are enforced on the server—never only hidden in the user interface.</p></div>{preview && <Badge className="w-fit border-0 bg-amber-300/10 text-[10px] tracking-[0.12em] text-amber-100">PREVIEW · NO MUTATIONS</Badge>}</header>

    <div className="mt-6 grid gap-6 xl:grid-cols-[minmax(0,1.35fr)_minmax(360px,.65fr)]">
      <div className="space-y-6">
        <section className="rounded-2xl border border-white/8 bg-[#0b1924] p-5"><div className="flex items-start justify-between gap-4"><div className="flex gap-3"><span className="grid h-9 w-9 place-items-center rounded-xl bg-violet-300/10 text-violet-100"><UsersRound className="h-4 w-4" /></span><div><h2 className="text-sm font-semibold text-slate-100">Role policy</h2><p className="mt-1 text-xs leading-5 text-slate-500">Role enforcement is centralized in every browser, TUI, CLI, API, MCP, and AgentZero server-side procedure.</p></div></div><Button size="sm" variant="outline" onClick={() => navigate(preview ? "/preview/administration/alert-rules" : "/administration/alert-rules")} className="border-white/10 bg-transparent text-slate-200 hover:bg-white/[0.06]">Alert rules</Button></div><div className="mt-5 divide-y divide-white/7 rounded-xl border border-white/7 bg-white/[0.025]">{policy.map((item) => <div key={item.role} className="px-4 py-4"><p className={cn("text-xs font-semibold", item.tone)}>{item.role}</p><p className="mt-1 text-[11px] leading-5 text-slate-500">{item.detail}</p></div>)}</div></section>
        <section className="rounded-2xl border border-white/8 bg-[#0b1924] p-5"><div className="flex items-start justify-between gap-4"><div className="flex gap-3"><span className="grid h-9 w-9 place-items-center rounded-xl bg-cyan-300/10 text-cyan-100"><ArchiveRestore className="h-4 w-4" /></span><div><h2 className="text-sm font-semibold text-slate-100">Backup control</h2><p className="mt-1 text-xs leading-5 text-slate-500">Primary-only backup work is fenced by a shared database lease. A shared mount is required before takeover can be validated.</p></div></div><Button disabled={preview || backup.isPending} onClick={() => backup.mutate({ includeRawTelemetry: false })} className="bg-cyan-300 text-[#071018] hover:bg-cyan-200">Queue summary backup</Button></div><div className="mt-5 grid gap-3 sm:grid-cols-3">{[["Retention", "10 daily copies"], ["Default scope", "Config + summaries"], ["Takeover", "Lease-fenced"]].map(([label, value]) => <div key={label} className="rounded-xl border border-white/7 bg-white/[0.025] p-3"><p className="text-[10px] tracking-[0.1em] text-slate-600">{label}</p><p className="mt-2 text-xs font-medium text-slate-300">{value}</p></div>)}</div></section>
        <section className="rounded-2xl border border-white/8 bg-[#0b1924] p-5"><div className="flex items-start gap-3"><span className="grid h-9 w-9 place-items-center rounded-xl bg-slate-300/10 text-slate-200"><LockKeyhole className="h-4 w-4" /></span><div><h2 className="text-sm font-semibold text-slate-100">Provisioning gates</h2><p className="mt-1 text-xs leading-5 text-slate-500">The following actions are intentionally deferred until shared Supabase Auth and the internal CA are configured.</p></div></div><div className="mt-5 grid gap-3 sm:grid-cols-2">{[{ icon: UserRoundPlus, title: "Invite user", detail: "Supabase invite-only magic-link setup pending." }, { icon: KeyRound, title: "Client API key", detail: "Key issuance is pending dedicated credential workflow validation." }, { icon: FileKey2, title: "Agent credential", detail: "Use the least-privilege enrollment CLI; never use owner credentials on a host." }, { icon: ShieldCheck, title: "Internal CA", detail: "Certificate issuance and bilateral endpoint validation pending." }].map((item) => <div key={item.title} className="rounded-xl border border-white/7 bg-white/[0.025] p-3"><item.icon className="h-4 w-4 text-slate-400" /><p className="mt-3 text-xs font-medium text-slate-300">{item.title}</p><p className="mt-1 text-[10px] leading-4 text-slate-600">{item.detail}</p></div>)}</div></section>
      </div>
      <aside className="rounded-2xl border border-white/8 bg-[#0b1924] p-5"><div className="flex items-center gap-3"><span className="grid h-9 w-9 place-items-center rounded-xl bg-emerald-300/10 text-emerald-200"><CheckCircle2 className="h-4 w-4" /></span><div><h2 className="text-sm font-semibold text-slate-100">Recent audit activity</h2><p className="mt-1 text-xs text-slate-500">Server-recorded events only</p></div></div><div className="mt-5 space-y-3">{preview ? <p className="rounded-xl border border-white/7 bg-white/[0.025] p-4 text-xs leading-5 text-slate-500">Development preview does not emulate audit events. Production actions are surfaced here from the server-side audit log.</p> : audits.data?.length ? audits.data.map((event) => <div key={event.id} className="rounded-xl border border-white/7 bg-white/[0.025] p-3"><div className="flex items-center justify-between gap-3"><p className="truncate text-xs font-medium text-slate-300">{event.action}</p><Badge className="border-0 bg-emerald-300/10 text-[10px] text-emerald-200">{event.outcome}</Badge></div><p className="mt-1 text-[10px] text-slate-600">{new Date(event.occurredAt).toLocaleString()} · {event.targetType}</p></div>) : <p className="rounded-xl border border-white/7 bg-white/[0.025] p-4 text-xs text-slate-500">No operator actions recorded in this session.</p>}</div></aside>
    </div>
  </div></DashboardLayout>;
}
