import DashboardLayout from "@/components/DashboardLayout";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Switch } from "@/components/ui/switch";
import { cn } from "@/lib/utils";
import { trpc } from "@/lib/trpc";
import { CheckCircle2, Clock3, DatabaseBackup, RefreshCw, ServerCog, SlidersHorizontal, TriangleAlert } from "lucide-react";
import { useMemo, useState } from "react";
import { toast } from "sonner";

export default function OperationsPage({ preview = false }: { preview?: boolean }) {
  const previewQuery = trpc.nodescope.fleet.preview.useQuery(undefined, { enabled: preview, refetchInterval: 5_000 });
  const liveQuery = trpc.nodescope.fleet.overview.useQuery(undefined, { enabled: !preview, refetchInterval: 5_000 });
  const fleet = preview ? previewQuery.data : liveQuery.data;
  const [interval, setInterval] = useState<number>(5);
  const [selectedHost, setSelectedHost] = useState<string>("global");
  const [baselineAcknowledged, setBaselineAcknowledged] = useState(false);
  const [runtimeEndpoint, setRuntimeEndpoint] = useState("");
  const setCollectionInterval = trpc.nodescope.configuration.setCollectionInterval.useMutation({
    onSuccess: (result) => { toast.success("Collection interval updated", { description: `Effective interval: ${result.effectiveIntervalSeconds}s.` }); liveQuery.refetch(); },
    onError: (error) => toast.error("Unable to update collection interval", { description: error.message }),
  });
  const refreshBaseline = trpc.nodescope.configuration.refreshStorageBaseline.useMutation({
    onSuccess: () => toast.success("Storage baseline refresh recorded"),
    onError: (error) => toast.error("Storage baseline refresh failed", { description: error.message }),
  });
  const approveRuntime = trpc.nodescope.runtimes.approve.useMutation({
    onSuccess: () => { toast.success("Runtime approved"); setRuntimeEndpoint(""); },
    onError: (error) => toast.error("Runtime approval failed", { description: error.message }),
  });
  const selectedHostRecord = useMemo(() => fleet?.hosts.find((host) => host.id === selectedHost), [fleet, selectedHost]);
  if (!fleet) return <DashboardLayout><div className="p-8 text-slate-400">Loading operations…</div></DashboardLayout>;
  const effectiveInterval = selectedHost === "global" ? fleet.globalIntervalSeconds : fleet.hostOverrides[selectedHost] ?? fleet.globalIntervalSeconds;

  return <DashboardLayout><div className="mx-auto max-w-[1320px] p-6 xl:p-8">
    <header className="flex flex-col gap-4 border-b border-white/8 pb-6 md:flex-row md:items-end md:justify-between"><div><div className="flex items-center gap-2 text-cyan-200"><ServerCog className="h-4 w-4" /><span className="text-xs font-medium tracking-[0.12em]">ROLE-PROTECTED OPERATIONS</span></div><h1 className="mt-3 text-3xl font-semibold tracking-[-0.035em] text-slate-50">Operational controls</h1><p className="mt-2 max-w-2xl text-sm leading-6 text-slate-400">Configuration changes are mediated server-side, audited, and never alter raw telemetry provenance.</p></div>{preview && <Badge className="w-fit border-0 bg-amber-300/10 text-[10px] tracking-[0.12em] text-amber-100">PREVIEW · CONTROLS DISABLED</Badge>}</header>

    <div className="mt-6 grid gap-6 xl:grid-cols-2">
      <section className="rounded-2xl border border-white/8 bg-[#0b1924] p-5"><div className="flex items-start gap-3"><span className="grid h-9 w-9 place-items-center rounded-xl bg-cyan-300/10 text-cyan-200"><SlidersHorizontal className="h-4 w-4" /></span><div><h2 className="text-sm font-semibold text-slate-100">Collection interval</h2><p className="mt-1 text-xs leading-5 text-slate-500">Set the global 1–60 second interval or a host-specific override. The agent reports its effective setting.</p></div></div><div className="mt-5 grid gap-4 sm:grid-cols-[1fr_150px]"><div><Label className="text-[10px] tracking-[0.1em] text-slate-500">SCOPE</Label><select value={selectedHost} onChange={(event) => { const value = event.target.value; setSelectedHost(value); setInterval(value === "global" ? fleet.globalIntervalSeconds : fleet.hostOverrides[value] ?? fleet.globalIntervalSeconds); }} className="mt-2 h-10 w-full rounded-lg border border-white/10 bg-white/[0.035] px-3 text-sm text-slate-200 outline-none focus:ring-2 focus:ring-cyan-300/50"><option value="global">Global default</option>{fleet.hosts.map((host) => <option key={host.id} value={host.id}>{host.name} override</option>)}</select></div><div><Label className="text-[10px] tracking-[0.1em] text-slate-500">SECONDS</Label><Input type="number" min={1} max={60} value={interval} onChange={(event) => setInterval(Math.max(1, Math.min(60, Number(event.target.value))))} className="mt-2 border-white/10 bg-white/[0.035] text-slate-100" /></div></div><div className="mt-5 flex items-center justify-between rounded-xl border border-white/7 bg-white/[0.025] p-3"><div><p className="text-xs text-slate-300">Current effective interval</p><p className="mt-1 text-[11px] text-slate-500">{selectedHostRecord ? `${selectedHostRecord.name} falls back to global when no override is set.` : "Applied fleet-wide unless a host override exists."}</p></div><span className="text-lg font-semibold text-cyan-100">{effectiveInterval}s</span></div><Button disabled={preview || setCollectionInterval.isPending} onClick={() => setCollectionInterval.mutate({ hostId: selectedHost === "global" ? undefined : selectedHost, intervalSeconds: interval })} className="mt-4 w-full bg-cyan-300 text-[#071018] hover:bg-cyan-200">Apply collection interval</Button></section>

      <section className="rounded-2xl border border-white/8 bg-[#0b1924] p-5"><div className="flex items-start gap-3"><span className="grid h-9 w-9 place-items-center rounded-xl bg-violet-300/10 text-violet-100"><DatabaseBackup className="h-4 w-4" /></span><div><h2 className="text-sm font-semibold text-slate-100">Storage baseline</h2><p className="mt-1 text-xs leading-5 text-slate-500">Learned mount and Docker-volume inventory is only refreshed after an operator acknowledges the current diff.</p></div></div><div className="mt-5 space-y-3">{fleet.hosts.map((host) => <div key={host.id} className="flex items-center justify-between rounded-xl border border-white/7 bg-white/[0.025] px-3 py-2.5"><div><p className="text-xs font-medium text-slate-300">{host.name}</p><p className="mt-1 text-[10px] text-slate-600">{host.storage.filter((storage) => storage.state === "learning" || storage.state === "missing").length} non-final mount states</p></div><Button disabled={preview || refreshBaseline.isPending || !baselineAcknowledged} size="sm" variant="outline" onClick={() => refreshBaseline.mutate({ hostId: host.id, acknowledgedDiff: baselineAcknowledged })} className="border-white/10 bg-transparent text-slate-200 hover:bg-white/[0.06]"><RefreshCw className="mr-1.5 h-3.5 w-3.5" />Refresh</Button></div>)}</div><label className="mt-4 flex cursor-pointer items-start gap-3 rounded-xl border border-amber-300/12 bg-amber-300/[0.045] p-3"><Switch checked={baselineAcknowledged} onCheckedChange={setBaselineAcknowledged} disabled={preview} /><span className="text-[11px] leading-5 text-amber-100">I reviewed the storage diff and approve replacing the learned baseline.</span></label></section>

      <section className="rounded-2xl border border-white/8 bg-[#0b1924] p-5"><div className="flex items-start gap-3"><span className="grid h-9 w-9 place-items-center rounded-xl bg-emerald-300/10 text-emerald-200"><CheckCircle2 className="h-4 w-4" /></span><div><h2 className="text-sm font-semibold text-slate-100">Runtime approvals</h2><p className="mt-1 text-xs leading-5 text-slate-500">Discovered endpoints remain non-routable until an Administrator explicitly approves them.</p></div></div><div className="mt-5 space-y-3">{fleet.hosts.flatMap((host) => host.runtimes.filter((runtime) => runtime.state === "discovered").map((runtime) => ({ host, runtime }))).map(({ host, runtime }) => <div key={`${host.id}-${runtime.endpoint}`} className="flex flex-col gap-3 rounded-xl border border-white/7 bg-white/[0.025] p-3 sm:flex-row sm:items-center sm:justify-between"><div><p className="text-xs font-medium text-slate-300">{runtime.kind} · {host.name}</p><p className="mt-1 truncate text-[10px] text-slate-600">{runtime.endpoint}</p></div><Button disabled={preview || approveRuntime.isPending} size="sm" variant="outline" className="border-white/10 bg-transparent text-slate-200 hover:bg-white/[0.06]" onClick={() => approveRuntime.mutate({ hostId: host.id, endpoint: runtime.endpoint, runtimeKind: runtime.kind })}>Approve</Button></div>)}</div><div className="mt-4"><Label className="text-[10px] tracking-[0.1em] text-slate-500">MANUAL ENDPOINT REVIEW</Label><Input value={runtimeEndpoint} onChange={(event) => setRuntimeEndpoint(event.target.value)} placeholder="https://approved-runtime.example/v1" className="mt-2 border-white/10 bg-white/[0.035] text-slate-100 placeholder:text-slate-700" /></div></section>

      <section className="rounded-2xl border border-amber-300/12 bg-[#0b1924] p-5"><div className="flex items-start gap-3"><span className="grid h-9 w-9 place-items-center rounded-xl bg-amber-300/10 text-amber-100"><TriangleAlert className="h-4 w-4" /></span><div><h2 className="text-sm font-semibold text-slate-100">Deferred validation gates</h2><p className="mt-1 text-xs leading-5 text-slate-500">These conditions require external infrastructure or real-hardware evidence and cannot be simulated by the console.</p></div></div><div className="mt-5 space-y-3">{["Supabase invite-only magic-link configuration", "Internal CA issuance and bilateral replica TLS verification", "Framework and Asus preflight plus 72-hour storage benchmark", "Shared backup mount availability and secondary takeover exercise"].map((item) => <div key={item} className="flex items-center gap-3 rounded-xl border border-white/7 bg-white/[0.025] p-3"><Clock3 className="h-4 w-4 text-amber-200" /><span className="text-xs text-slate-400">{item}</span></div>)}</div></section>
    </div>
  </div></DashboardLayout>;
}
