/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/fleet": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get current fleet health and capacity state. */
        get: operations["getFleetOverview"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/hosts/{hostId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get platform-aware host telemetry and inventory. */
        get: operations["getHostDetail"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/configuration/collection-interval": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** Set the global or a host-specific collection interval. */
        put: operations["setCollectionInterval"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/storage-baselines/{hostId}/refresh": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Refresh the learned storage baseline after presenting its diff. */
        post: operations["refreshStorageBaseline"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/alerts/{alertId}/acknowledge": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Acknowledge an active alert. */
        post: operations["acknowledgeAlert"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/audit": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List immutable audit events visible to the caller. */
        get: operations["listAuditEvents"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        FleetOverview: {
            /** Format: date-time */
            generatedAt: string;
            activeAlertCount: number;
            hosts: components["schemas"]["HostSummary"][];
            replicaHealth: components["schemas"]["ReplicaHealth"][];
        };
        HostSummary: {
            id: string;
            name: string;
            platform: string;
            freshness: components["schemas"]["Freshness"];
            metrics: components["schemas"]["MetricValue"][];
        };
        HostDetail: components["schemas"]["HostSummary"] & {
            inventory: Record<string, never>;
            memoryViews: components["schemas"]["MetricValue"][];
        };
        Freshness: {
            /** @enum {string} */
            state: "fresh" | "stale" | "unavailable";
            /** Format: date-time */
            observedAt: string;
            ageSeconds?: number;
        };
        MetricValue: {
            name: string;
            unit?: string;
            /** @description Omitted or null for unavailable or unsupported values; consumers must not coerce null to zero. */
            value?: number | null;
            /** @enum {string} */
            quality: "fresh" | "stale" | "unavailable" | "unsupported" | "estimated" | "experimental";
            source: string;
            semantics: string;
            /** Format: date-time */
            observedAt: string;
        };
        ReplicaHealth: {
            id: string;
            /** @enum {string} */
            role: "preferred" | "secondary";
            /** @enum {string} */
            status: "healthy" | "degraded" | "unavailable";
            /** Format: date-time */
            observedAt: string;
        };
        CollectionIntervalChange: {
            /** @description Omit for global configuration; set for a host override. */
            hostId?: string;
            intervalSeconds: number;
        };
        OperationReceipt: {
            operationId: string;
            auditEventId: string;
            /** @enum {string} */
            state: "pending" | "acknowledged" | "completed" | "failed";
        };
        AuditEvent: {
            id: string;
            /** @enum {string} */
            actorType: "user" | "client" | "agent" | "system";
            actorId: string;
            action: string;
            /** @enum {string} */
            outcome: "intent" | "acknowledged" | "completed" | "failed" | "denied";
            /** Format: date-time */
            occurredAt: string;
        };
        Problem: {
            /** Format: uri-reference */
            type: string;
            title: string;
            status: number;
            requestId: string;
        };
    };
    responses: {
        /** @description Authentication is required. */
        Unauthorized: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": components["schemas"]["Problem"];
            };
        };
        /** @description The authenticated actor lacks the required role or capability. */
        Forbidden: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": components["schemas"]["Problem"];
            };
        };
        /** @description The requested resource does not exist or is not visible. */
        NotFound: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": components["schemas"]["Problem"];
            };
        };
        /** @description The request is syntactically valid but violates a NodeScope rule. */
        ValidationError: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": components["schemas"]["Problem"];
            };
        };
    };
    parameters: {
        HostId: string;
        AlertId: string;
    };
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    getFleetOverview: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Fleet overview. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FleetOverview"];
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
        };
    };
    getHostDetail: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                hostId: components["parameters"]["HostId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Host detail. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HostDetail"];
                };
            };
            404: components["responses"]["NotFound"];
        };
    };
    setCollectionInterval: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CollectionIntervalChange"];
            };
        };
        responses: {
            /** @description Desired state recorded and audit intent created. */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OperationReceipt"];
                };
            };
            400: components["responses"]["ValidationError"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
        };
    };
    refreshStorageBaseline: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                hostId: components["parameters"]["HostId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Desired baseline refresh recorded. */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OperationReceipt"];
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
        };
    };
    acknowledgeAlert: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                alertId: components["parameters"]["AlertId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Alert acknowledgement recorded. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuditEvent"];
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
        };
    };
    listAuditEvents: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Audit events. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        items: components["schemas"]["AuditEvent"][];
                    };
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
        };
    };
}
